config/routes.rb
InvoicesSite::Application.routes.draw do

  devise_for :users

  root 'static_pages#home'

  authenticated :user do
    root 'users#show', as: :authenticated_root

    resources :contacts

    resources :contact_types

    resources :client_types

    resources :clients

    resources :tasks

    resources :work_logs, :except => [:index, :new, :create]
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      render 'dashboard.html.haml'
    else
      render 'home.html.haml'
    end
  end

  def dashboard
  end
end

app/views/static_pages/dashboard.html.haml
= provide :title, "Hello, #{current_user.username}!"
%div.row
  .large-7.columns
    %table
      %thead
        %tr
          %th{colspan: 6} Tasks
        %tr
          %th Name
          %th Client
          %th Due Date
          %th{colspan: 3} Actions
      - unless Task.all.nil?
        - Task.incomplete.each do |task|
          - @current_class = task
          %tr
            %td= task.name
            %td= task.client
            %td= task_due task.due_date
            = render 'common/index_links'
      %tfoot
        %tr
          %td{colspan: 6}= link_to 'New Task', new_task_path
  .large-5.columns
    %table
      %thead
        %tr
          %th{colspan: 6} Completed Tasks
        %tr
          %th Name
          %th Client
      - unless Task.all.nil?
        -# Task.where(status: 0).includes(:client).each do |task|
        - Task.complete.each do |task|
          %tr
            %td= task.name
            %td= task.client
      %tfoot
%div.row
  .large-12.columns
    %table
      %thead
        %tr
          %th{colspan: 7} Contacts
        %tr
          %th Name
          %th.hide-for-small Title
          %th Email
          %th Client
          %th{colspan: 3} Actions
      - Contact.all.includes(:client).each do |contact|
        - @current_class = contact
        %tr
          %td= contact.name
          %td.hide-for-small= contact.title
          %td= contact.email
          %td= contact.client
          = render 'common/index_links'
      %tfoot
        %tr
          %td{colspan: 7}= link_to 'New Contact', new_contact_path
%div.row
  .large-5.columns
    %table
      %thead
        %tr
          %th{colspan: 5} Clients
        %tr
          %th Name
          %th Type
          %th{colspan: 3} Actions
      - Client.order('name ASC').includes(:client_type).each do |client|
        - @current_class = client
        %tr
          %td= client.name
          %td= client.client_type
          = render 'common/index_links'
      %tfoot
        %tr
          %td{colspan: 5}= link_to 'New Client', new_client_path

app/views/static_pages/home.html.haml
= provide :title, "Home"