config/routes.rb
InvoicesSite::Application.routes.draw do

  devise_for :users

  root 'static_pages#home'

  authenticated :user do
    root 'users#show', as: :authenticated_root

    resources :contacts

    resources :contact_types

    resources :client_types

    resources :clients

    resources :tasks

    resources :work_logs, :except => [:index, :new, :create]
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :client_type
  has_many :contacts
  accepts_nested_attributes_for :contacts, allow_destroy: true
  validates :name, presence: true
  validates :client_type_id, presence: true

  def to_s
    name
  end
end

app/models/client_type.rb
class ClientType < ActiveRecord::Base
  has_many :clients

  def to_s
    return self.name
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  layout 'devise'

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.order("name ASC").includes(:client_type)
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :client_type_id, contacts_attributes: [:id, :name, :contact_type, :title, :email, :phone, :skype, :im, :_destroy])
    end
end

app/views/clients/_form.html.haml
= simple_form_for(@client) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/clients/edit.html.haml
= provide :title, 'Editing Client'
= render 'common/edit_form'

= link_to 'Show', @client
\|
= link_to 'Back', clients_path

app/views/clients/index.html.haml
= provide :title, "Listing Clients"

%table
	%thead
		%tr
			%th Name
			%th Type
			%th{colspan: 3} Actions
	- @clients.each do |client|
		- @current_class = client
		%tr
			%td= client.name
			%td= client.client_type
			= render 'common/index_links'

%br

= link_to 'New Client', new_client_path

app/views/clients/new.html.haml
= provide :title, "New Client"
= render 'common/new_form'

app/views/clients/show.html.haml
:css
	h2 {
		margin-bottom: 0;
		border-bottom: 1px solid black;
	}
= provide :title, @client.name
%fieldset
	%legend Contacts
	- @client.contacts.each do |contact|
		%table
			%tr
				%th{colspan: 2} #{contact}, #{contact.title}
			%tr
				%th Phone:
				%td= contact.formatted_phone
			%tr
				%th Email:
				%td= contact.email
			%tr
				%th Skype:
				%td= contact.skype
			%tr
				%th IM:
				%td= contact.im
			%tr
				%td{colspan: 2}= link_to 'Edit this contact', edit_contact_path(contact)
= link_to 'Edit', edit_client_path(@client)
\|
= link_to 'Back', clients_path