config/routes.rb
InvoicesSite::Application.routes.draw do

  devise_for :users

  root 'static_pages#home'

  authenticated :user do
    root 'users#show', as: :authenticated_root

    resources :contacts

    resources :contact_types

    resources :client_types

    resources :clients

    resources :tasks

    resources :work_logs, :except => [:index, :new, :create]
  end

end

app/views/common/_auth_button.html.haml
- if user_signed_in?
  %li.divider
  %li.has-dropdown
    = link_to "Hello, #{current_user.username}!", "#"
    %ul.dropdown
      %li= link_to "Edit My Account", edit_user_registration_path
      %li= link_to 'Log out', destroy_user_session_path, :method => :delete
- else
  %li.divider
  %li= link_to "Log in", new_user_session_path

app/views/common/_devise_edit_form.html.haml
-# Edit User
- if current_page? '/users/edit'
  = simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f|
    = devise_error_messages!
    %fieldset
      %legend= content_for?(:title) ? yield(:title) : "Untitled"
      = f.error_notification
      %div.form-inputs
        = f.input :username, required: true, autofocus: true
        = f.input :email, required: true
        - if devise_mapping.confirmable? && resource.pending_reconfirmation?
          %p Currently waiting confirmation for: #{resource.unconfirmed email}
        = f.input :password, autocomplete: "off", hint: "Leave it blank if you don't want to change it", required: false
        = f.input :password_confirmation, required: false
        = f.input :current_password, hint: "We need your current password to confirm your changes", required: true
      %div.form-actions
        = f.button :submit, content_for?(:submitmsg) ? yield(:submitmsg) : yield(:title)
  %h3 Cancel my account
  %p Unhappy? #{link_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?"}, :method => :delete }
  = link_to 'Back', :back
  %hr

-# Change Password
- if current_page? '/users/password/edit'
  = simple_form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => { :method => :put }) do |f|
    = devise_error_messages!
    %fieldset
      %legend= content_for?(:title) ? yield(:title) : "Untitled"
      = f.error_notification
      = f.input :reset_password_token, as: :hidden
      = f.full_error :reset_password_token
      %div.form-inputs
        = f.input :password, label: 'New Password', required: true, autofocus: true
        = f.input :password_confirmation, label: 'Confirm your new password', required: true
      %div.form-actions
        = f.button :submit, content_for?(:submitmsg) ? yield(:submitmsg) : yield(:title)

app/views/common/_devise_form.html.haml
:ruby
  @legend_title = content_for?(:title) ? yield(:title) : "Untitled"
  @submit_title = content_for?(:submitmsg) ? yield(:submitmsg) : yield(:title)

-# Sign in
- if current_page? '/users/sign_in'
  = simple_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f|
    = devise_error_messages!
    %fieldset
      %legend= @legend_title
      = f.error_notification
      %div.form-inputs
        = f.input :email, required: false, autofocus: true
        = f.input :password, required: false
        = f.input :remember_me, as: :boolean if devise_mapping.rememberable?
      %hr
      %div.form-actions
        = f.button :submit, @submit_title

-# Sign up
- if current_page? '/users/sign_up'
  = simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|
    %fieldset
      %legend= @legend_title
      = f.error_notification
      %div.form-inputs
        = f.input :username, required: true, autofocus: true
        = f.input :email, required: true
        = f.input :password, required: true
        = f.input :password_confirmation, required: true
      %hr
      %div.form-actions
        = f.button :submit, @submit_title

-# Forgot password
- if current_page? '/users/password/new'
  = simple_form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => { :method => :post }) do |f|
    %fieldset
      %legend= @legend_title
      = f.error_notification
      %div.form_inputs
        = f.input :email, required: true, autofocus: true
      %hr
      %div.form-actions
        = f.button :submit, @submit_title

-# Resend Confirmation Instructions
- if current_page? '/users/confirmation/new'
  = simple_form_for(resource, :as => resource_name, :url => confirmation_path(resource_name), :html => { :method => :post }) do |f|
    %fieldset
      %legend= content_for?(:title) ? yield(:title) : "Untitled"
      = f.error_notification
      = f.full_error :confirmation_token
      %div.form_inputs
        = f.input :email, required: true, autofocus: true
      %div.form_actions
        = f.button :submit, @submit_title

app/views/common/_edit_form.html.haml
:css
	.label {
		background: none;
		color: #222;
	}
:ruby
	@legend_title = content_for?(:title) ? yield(:title) : "Untitled"
	@submit_title = content_for?(:submitmsg) ? yield(:submitmsg) : yield(:title)

-# Edit Client
- if current_page? controller: 'clients', action: 'edit'
	
	= simple_nested_form_for(@client) do |f|
		%fieldset
			%legend= @legend_title
			%div.form-inputs
				= f.input :name
				= f.input :client_type_id, as: :select, collection: ClientType.all
				= f.simple_fields_for :contacts do |contact|
					%fieldset
						%legend Contacts
						= contact.input :name
						= contact.association :contact_type
						= contact.input :title
						= contact.input :email
						= contact.input :phone
						= contact.input :skype
						= contact.input :im
						= contact.link_to_remove 'Remove this contact'
			%div.form-actions
				= f.button :submit
				= f.link_to_add 'Add Contact', :contacts
-# Edit Client Type
- if current_page? controller: 'client_types', action: 'edit'
	= simple_form_for(@client_type) do |f|
		%fieldset
			%legend= @legend_title
			%div.form-inputs
				= f.input :name
			%div.form-actions
				= f.button :submit

-# Edit Contact Type
- if current_page? controller: 'contact_types', action: 'edit'
	= simple_form_for(@contact_type) do |f|
		%fieldset
			%legend= @legend_title
			%div.form-inputs
				= f.input :name
			%div.form-actions
				= f.button :submit

app/views/common/_index_links.html.haml
%td= link_to 'Show', @current_class
%td= link_to 'Edit', controller: @current_class.class.table_name, action: 'edit', id: @current_class
%td= link_to 'Destroy', @current_class, method: :delete, data: { confirm: 'Are you sure?' }

app/views/common/_navigation.html.haml
/ Navigation bar
%nav.top-bar
  %ul.title-area
    %li.name
      %h1= link_to "#{InvoicesConfig::AppDetails::NAME}", '/'
    / Remove the class "menu-icon" to get rid of the menu icon.  Take out "Menu" to just have the icon alone.
    %li.toggle-topbar.menu-icon
      = link_to 'Menu', ''
  %section.top-bar-section
    %ul.left
      %li.divider
      %li= link_to "Home", '/'
      -# Clients
      %li.has-dropdown.not-click
        = link_to 'Clients', '/clients' if user_signed_in?
        %ul.dropdown
          %li= link_to 'Manage Client Types', client_types_path
      -# Contacts
      %li.has-dropdown
        = link_to 'Contacts', '/contacts' if user_signed_in?
        %ul.dropdown
          %li= link_to "Manage Contact Types", contact_types_path
      -# Tasks
      %li= link_to 'Tasks', '/tasks' if user_signed_in?
    / Right nav section
    %ul.right
      = render 'common/auth_button'

app/views/common/_new_form.html.haml
:ruby
	@legend_title = content_for?(:title) ? yield(:title) : "Untitled"
	@submit_title = content_for?(:submitmsg) ? yield(:submitmsg) : yield(:title)

-# New Client
- if current_page? '/clients/new'
	= simple_form_for(@client) do |f|
		%fieldset
			%legend= @legend_title
			%div.form-inputs
				= f.input :name
				= f.input :client_type_id, as: :select, collection: ClientType.all
			%div.form-actions
				= f.button :submit
	= link_to 'Back', clients_path
-# New Client Type
- if current_page? '/client_types/new'
	= simple_form_for(@client_type) do |f|
		%fieldset
			%legend= @legend_title
			%div.form-inputs
				= f.input :name
			%div.form-actions
				= f.button :submit
-# New Contact Type
- if current_page? '/contact_types/new'
	= simple_form_for(@contact_type) do |f|
		%fieldset
			%legend= @legend_title
			%div.form-inputs
				= f.input :name
			%div.form-actions
				= f.button :submit

app/views/common/_show_form.html.haml
/ TODO: Remove this page
- if current_page? '/clients'
	%table
		%tr
			%th Name
			%th{colspan: 3} Actions
		- @clients.each do |client|
			%tr
				%td= client.name
				%td= link_to 'Show', client
				%td= link_to 'Edit', edit_client_path(client)
				%td= link_to 'Destroy', client, :method => :delete, :data => { confirm: 'Are you sure?' }
	%br
	= link_to 'New Client', new_client_path

- if current_page? '/client_types'
	%table
		%tr
			%th Name
			%th{colspan: 3} Actions
		- @client_types.each do |client_type|
			%tr
				%td= client_type.name
				%td= link_to 'Show', client_type
				%td= link_to 'Edit', edit_client_type_path(client_type)
				%td= link_to 'Destroy', client_type, :method => :delete, :data => { confirm: 'Are you sure?' }
	%br
	= link_to 'New Client Type', new_client_type_path